yolov7 v0.1
wang-xinyu/tensorrtx pull request #1105
Opened 2022-09-18 09:04 UTC by lindsayshuo

yolov7 v0.1

2022-09-19 02:01 UTC, fire717 commented
1. your gen_wts.py not read args -w -o but hard encode "yolov7.pt"
2. I run -s yolov7t.wts yolov7t.engine t ,got error `Could not compute dimensions for (Unnamed Layer* 187) [Convolution]_output, because the network is not vali`

2022-09-19 02:41 UTC, wang-xinyu requested changes
@lindsayshuo Thanks.

Please remove all the binary files, including .engine and .jpg.
For the sample images, we can create a soft link, like yolov5.

2022-09-19 02:50 UTC, wang-xinyu requested changes

2022-09-19 02:50 UTC, wang-xinyu commented on yolov7/yololayer.h
> +    static constexpr int CLASS_NUM = 80; //====�޸�Ϊ�Լ������=====
please remove this in-line comment.

2022-09-19 02:50 UTC, wang-xinyu commented on yolov7/yolov7.cpp
> +//----------------------------yolov7e6e网络模型结构搭建---------------------------------------
Chinese

2022-09-19 02:50 UTC, wang-xinyu commented on yolov7/common.hpp
> +//=========== 将预测信息（相对img_size 640）映射回原图 img0 size,对应scale_coords ============
Chinese

2022-09-19 07:49 UTC, merged

2022-09-20 01:51 UTC, lindsayshuo commented
> 1. your gen_wts.py not read args -w -o but hard encode "yolov7.pt"
> 
>     2. I run -s yolov7t.wts yolov7t.engine t ,got error `Could not compute dimensions for (Unnamed Layer* 187) 

> 1. your gen_wts.py not read args -w -o but hard encode "yolov7.pt"
> 
>     2. I run -s yolov7t.wts yolov7t.engine t ,got error `Could not compute dimensions for (Unnamed Layer* 187) [Convolution]_output, because the network is not vali`



> 1. your gen_wts.py not read args -w -o but hard encode "yolov7.pt"
> 
>     2. I run -s yolov7t.wts yolov7t.engine t ,got error `Could not compute dimensions for (Unnamed Layer* 187) [Convolution]_output, because the network is not vali`

as for gen_wts.py, you can refer  to tensorrtx/yolov5;
you can use this latest code :git clone https://github.com/WongKinYiu/yolov7.git;

2022-09-20 02:09 UTC, lindsayshuo commented
> > 1. your gen_wts.py not read args -w -o but hard encode "yolov7.pt"
> >    
> >    2. I run -s yolov7t.wts yolov7t.engine t ,got error `Could not compute dimensions for (Unnamed Layer* 187)
> 
> > 1. your gen_wts.py not read args -w -o but hard encode "yolov7.pt"
> >    
> >    2. I run -s yolov7t.wts yolov7t.engine t ,got error `Could not compute dimensions for (Unnamed Layer* 187) [Convolution]_output, because the network is not vali`
> 
> > 1. your gen_wts.py not read args -w -o but hard encode "yolov7.pt"
> >    
> >    2. I run -s yolov7t.wts yolov7t.engine t ,got error `Could not compute dimensions for (Unnamed Layer* 187) [Convolution]_output, because the network is not vali`
> 
> as for gen_wts.py, you can refer to tensorrtx/yolov5; you can use this latest code :git clone https://github.com/WongKinYiu/yolov7.git;

for yolov7.pt :  ./yolov7  -s ../yolov7.wts  ../yolov7.engine  v7

for yolov7-tiny.pt:  ./yolov7  -s ../yolov7-tiny.wts  ../yolov7.engine  t

2022-09-20 02:15 UTC, lindsayshuo commented
> 1. your gen_wts.py not read args -w -o but hard encode "yolov7.pt"
> 
>     2. I run -s yolov7t.wts yolov7t.engine t ,got error `Could not compute dimensions for (Unnamed Layer* 187) [Convolution]_output, because the network is not vali`

for yolov7.pt : ./yolov7 -s ../yolov7.wts ../yolov7.engine v7

for yolov7-tiny.pt: ./yolov7 -s ../yolov7-tiny.wts ../yolov7.engine t