Add an engine export that can customize category models
wang-xinyu/tensorrtx pull request #1322
Opened 2023-07-05 01:13 UTC by lindsayshuo

2023-07-05 02:15 UTC, wang-xinyu requested changes

2023-07-05 02:15 UTC, wang-xinyu commented on yolov8/src/model.cpp
>  IHostMemory* buildEngineYolov8n(const int& kBatchSize, IBuilder* builder,
config.h已经定义了kBatchSize，这里函数参数改为batchsize吧

2023-07-05 02:15 UTC, wang-xinyu commented on yolov8/src/model.cpp
> +    int firstDimension = shuffle22_0_shape.d[0];
局部变量命名用全小写和下划线吧，可以改为：first_dim

2023-07-05 02:36 UTC, wang-xinyu approved these changes

2023-07-05 02:37 UTC, merged

2023-07-12 05:31 UTC, FunnyWii commented
请问这个针对自己训练的模型的改动，有没有测试过呀？
我自己的模型有10个class，修改了const static int kNumClass = 10;
依然报错 kernel weights has count 36864 but 5760 was expected。

2023-07-12 05:42 UTC, lindsayshuo commented
> 请问这个针对自己训练的模型的改动，有没有测试过呀？ 我自己的模型有10个class，修改了const static int kNumClass = 10; 依然报错 kernel weights has count 36864 but 5760 was expected。

我这边测试了32分类的没问题，可以提供下你的pt