retinafaceAntiCov tensorrt8
wang-xinyu/tensorrtx pull request #1366
Opened 2023-09-23 12:33 UTC by lindsayshuo

retinafaceAntiCov tensorrt8

2023-09-26 04:43 UTC, wang-xinyu requested changes

2023-09-26 04:43 UTC, wang-xinyu commented on retinafaceAntiCov/decode.h
> +using namespace std;
google编程规范一般不允许写using namespace std，引用的时候加std::，这块要不改下吧

2023-09-26 09:56 UTC, lindsayshuo commented
retinafaceAntiCov/decode.h已改




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wang-xinyu/tensorrtx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月26日(星期二) 中午12:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wang-xinyu/tensorrtx] retinafaceAntiCov tensorrt8 (PR #1366)





 
@wang-xinyu requested changes on this pull request.
 
 
In retinafaceAntiCov/decode.h:
 &gt;  #include "NvInfer.h" +#include "macros.h" + +using namespace std;  
google编程规范一般不允许写using namespace std，引用的时候加std::，这块要不改下吧
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2023-09-27 10:29 UTC, wang-xinyu approved these changes

2023-09-27 10:29 UTC, merged