refinedet
wang-xinyu/tensorrtx pull request #441
Opened 2021-03-12 10:11 UTC by wuzuowuyou

refinedet

2021-03-14 02:37 UTC, wang-xinyu requested changes

2021-03-14 02:37 UTC, wang-xinyu commented on refinedet/gen_wts_refinedet.py
> +
why so many empty lines?

2021-03-14 02:37 UTC, wang-xinyu commented on refinedet/refinedet.cpp
> +    if (r.x < 0) r.x = 0;
pls do not use Chinese in code.  pls check all.

2021-03-14 02:37 UTC, wang-xinyu commented on refinedet/README.md
> +
why you paste configure.h in readme?

2021-03-15 04:02 UTC, wuzuowuyou commented
Re submit

2021-03-15 04:05 UTC, wuzuowuyou commented
1

2021-03-15 04:54 UTC, merged