Support TSM-R50 Python API
wang-xinyu/tensorrtx pull request #488
Opened 2021-04-16 12:18 UTC by irvingzhang0512

Will add C++ API next week.

2021-04-16 12:29 UTC, wang-xinyu requested changes
Hi, pretty cool, thanks for the PR.
pls remove .gitignore and demo.mp4, and can you provide a link in readme to download demo.mp4?

2021-04-16 13:55 UTC, irvingzhang0512 commented
> Hi, pretty cool, thanks for the PR.
> pls remove .gitignore and demo.mp4, and can you provide a link in readme to download demo.mp4?

OK.
I plan to test this pr on TensorRT 5.1 first, then fix .gitignore * demo.mp4.

2021-04-18 08:30 UTC, wang-xinyu approved these changes

2021-04-18 08:30 UTC, merged

2024-09-04 11:34 UTC, knowlessthanenough commented
I know it have been 3 years. But I have a question about the tsm_r50.py. In the original paper the last layer is a classifier but here I see it do fully connect than reshape to[segment, output size ] than do avg on output size dimensions which make it to 1 . Finally do softmax . The output now become [ batch size, segment] which is different from the original paper . I want to know if I understand it wrong?